name: Run unit tests

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps: 
      - name: Cloning repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: npm install
        run: npm install
      - name: Run Eslint
        run: npm run lint
      - name: Run tests
        run: npm run test